package com.github.barry.akali.test.dto.request;

import com.github.barry.akali.base.dto.BaseRequestDto;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

/**
 *  User Dto generated by auto
 * 这是类的注释
 *
 * @author quansr
 * Created On 2020-04-23.
 */
@Data
@ToString(callSuper = true)
@EqualsAndHashCode(callSuper = false)
public class UserRequestDto extends BaseRequestDto {

    /**
     * 
     */
    private static final long serialVersionUID = -1L;

    /**
     * TODO 字段信息描述
     */
    private String username;

    /**
     * TODO 字段信息描述
     */
    private String email;

    /**
     * TODO 字段信息描述
     */
    private String password;

    /**
     * TODO 字段信息描述
     */
    private Integer age;

}