package com.github.barry.akali.test.repository;

import org.springframework.data.rest.core.annotation.RepositoryRestResource;

import com.github.barry.akali.base.BaseRepository;

import com.github.barry.akali.entity.User;

/**
 * repository for User generated by jpa-codegen
 * 这是类的注释
 *
 * @author quansr
 * Created On 2020-04-23.
 */
@RepositoryRestResource(path = "user", itemResourceRel = "resource", collectionResourceRel = "resources")
public interface UserRepository extends BaseRepository<User, Integer> {


}