package com.github.barry.akali.test.dto.response;

import org.springframework.hateoas.server.core.Relation;

import com.github.barry.akali.base.dto.BaseResponseDto;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

/**
 *  User generated by auto
 * 这是类的注释
 *
 * @author quansr
 * Created On 2020-04-23.
 */
@Data
@ToString(callSuper = true)
@EqualsAndHashCode(callSuper = false)
@Relation(collectionRelation = "resources")
public class UserResponseDto extends BaseResponseDto {

    /**
     * 
     */
    private static final long serialVersionUID = -1L;

    /**
     * TODO 字段信息描述
     */
    private String username;

    /**
     * TODO 字段信息描述
     */
    private String email;

    /**
     * TODO 字段信息描述
     */
    private String password;

    /**
     * TODO 字段信息描述
     */
    private Integer age;

}