package ${packageName};


<#if hasDateParam>
import org.springframework.format.annotation.DateTimeFormat;
import com.github.barry.akali.base.utils.IConstants;
</#if>

import com.github.barry.akali.base.dto.BaseRequestDto;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
<#list imports as import>
import ${import};
</#list>

/**
 *  ${entity.className} Dto generated by auto
 * ${entity.comment}
 *
 * @author ${author}
 * @since ${date}.
 */
@Data
@ToString(callSuper = true)
@EqualsAndHashCode(callSuper = false)
public class ${className} extends BaseRequestDto {

    /**
     * 
     */
    private static final long serialVersionUID = -1L;

    <#if entity.fields?? && (entity.fields?size > 0)>
    <#list entity.fields as f>
    /**
     * ${f.comment}
     */
    <#if f.className == 'LocalDateTime'>
    @DateTimeFormat(pattern = IConstants.DATE_TIME_MS_FORMAT)
    </#if>
    private ${f.className} ${f.name};

    </#list>
    </#if>
}