package ${packageName};

import java.util.Map;

import org.springframework.util.StringUtils;
import com.github.barry.akali.base.dto.BaseSearchDto;
<#if hasDateParam>
import org.springframework.format.annotation.DateTimeFormat;
</#if>
import lombok.Data;
import lombok.EqualsAndHashCode;
<#list imports as import>
import ${import};
</#list>

/**
 *  ${entity.className} Dto generated by auto
 * ${entity.comment}
 *
 * @author ${author}
 * @since ${date}.
 */
@Data
@EqualsAndHashCode(callSuper = false)
public class ${className} extends BaseSearchDto{


    <#if entity.fields?? && (entity.fields?size > 0)>
    <#list entity.fields as f>
    /**
     * ${f.comment}
     */
    <#if f.className == 'LocalDateTime'>
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    </#if>
    private ${f.className} ${f.name};

    </#list>
    </#if>
    /**
     * 实现父类的查询条件过滤
     * 
     */
    @Override
    public void buildSearchParams(Map<String, Object> map) {
        <#if entity.fields?? && (entity.fields?size > 0)>
    <#list entity.fields as f>
    <#if f.className == "String">
        if (StringUtils.hasText(this.${f.name})) {
            super.putNoNull("LIKE_${f.name}", this.${f.name}, map);
        }
    <#else>
        super.putNoNull("EQ_${f.name}", this.${f.name}, map);
    </#if>
    </#list>
    </#if>
    }

}