package com.github.barry.akali.test.service;

import java.util.List;
import java.util.Map;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.Sort.Direction;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.github.barry.akali.base.dto.BaseSearchDto;
import com.github.barry.akali.base.BaseService;
import com.github.barry.akali.base.utils.PageInfo;
import com.github.barry.akali.entity.User;
import com.github.barry.akali.test.dto.request.UserRequestDto;
import com.github.barry.akali.test.dto.response.UserResponseDto;
import com.github.barry.akali.test.dto.search.UserSearchDto;

import lombok.extern.slf4j.Slf4j;

/**
 * service for User generated by jpa-codegen
 * 这是类的注释
 *
 * @author quansr
 * Created On 2020-04-23.
 */
@Slf4j
@Service
@Transactional(readOnly = true)
public class UserService extends BaseService<User, Integer> {

    //@Autowired
    //private UserRepository userRepository;

    /**
     * 创建实体
     *
     * @param userRequestDto 表单
     * @return 实体对象
     */
    @Transactional(readOnly = false)
    public UserResponseDto create(UserRequestDto userRequestDto) {
        User user = new User();
        super.mapper(user, userRequestDto);
        user = super.save(user);
        return super.mapperByClass(user, UserResponseDto.class);
    }

    /**
     * 删除实体
     * @param id 实体id
     */
    @Override
    @Transactional(readOnly = false)
    public void deleteById(Integer id) {
        super.findById(id).ifPresent(t -> {
            t.setIsActive(Boolean.FALSE);
            super.save(t);
        });
    }

    /**
     * 根据主键集合批量删除
     * 
     * @param ids
     */
    @Transactional(readOnly = false)
    public void deleteByIds(List<Integer> ids) {
        super.deleteAllById(ids);
    }

    /**
     * 更新实体
     *
     * @param dto 表单
     * @param id      实体id
     * @return 实体对象
     */
    @Transactional(readOnly = false)
    public UserResponseDto update(Integer id, UserRequestDto userRequestDto) {
        User user = super.findById(id).get();
        super.mapper(user, userRequestDto);
        user = super.save(user);
        return super.mapperByClass(user, UserResponseDto.class);
    }

    /**
     * 获取一个实体对象
     *
     * @param id 实体id
     * @return 实体对象
     */
    public UserResponseDto details(Integer id) {
        User user = super.findById(id).get();
        return super.mapperByClass(user, UserResponseDto.class);
    }

    /**
     * 分页列表
     * 
     * @param searchParams 搜索参数
     * @param pageInfo     分页信息
     * @return 分页列表
     */
    public Page<UserResponseDto> getPageList(Map<String, Object> searchParams, PageInfo pageInfo) {
        BaseSearchDto searchDto = super.conver(searchParams, UserSearchDto.class);
        Map<String, Object> searchMap = searchDto.getSearchParams();
        log.debug("User的分页搜索的条件是={},排序的字段为={}", searchMap, pageInfo.getSortType());
        Page<User> page = super.findPageBySort(searchMap, pageInfo.getNumber(), pageInfo.getSize(), Direction.DESC,
                pageInfo.getSortType().split(","));
        Page<UserResponseDto> respPage = new PageImpl<>(super.mapperList(page.getContent(), UserResponseDto.class),
                page.getPageable(), page.getTotalElements());
        return respPage;
    }

    /**
     * 根据搜索条件搜索所有符合条件的信息列表
     * 
     * @param searchParams 搜索参数
     * @return 信息列表
     */
    public List<UserResponseDto> findByParams(Map<String, Object> searchParams, String sortTypes) {
        BaseSearchDto searchDto = super.conver(searchParams, UserSearchDto.class);
        log.debug("User的不分页搜索的参数是={}", searchDto);
        List<User> list = super.findAllBySort(searchDto.getSearchParams(), Direction.DESC, sortTypes.split(","));
        return super.mapperList(list, UserResponseDto.class);
    }

}