package com.github.barry.akali.test.dto.search;

import java.util.Map;

import org.springframework.util.StringUtils;

import com.github.barry.akali.base.dto.BaseSearchDto;

import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 *  User Dto generated by auto
 * 这是类的注释
 *
 * @author quansr
 * Created On 2020-04-23.
 */
@Data
@EqualsAndHashCode(callSuper = false)
public class UserSearchDto extends BaseSearchDto{


    /**
     * TODO 字段信息描述
     */
    private String username;

    /**
     * TODO 字段信息描述
     */
    private String email;

    /**
     * TODO 字段信息描述
     */
    private String password;

    /**
     * TODO 字段信息描述
     */
    private Integer age;

    /**
     * 实现父类的查询条件过滤
     * 
     */
    @Override
    public void buildSearchParams(Map<String, Object> map) {
        if (StringUtils.hasText(this.username)) {
            super.putNoNull("LIKE_username", this.username, map);
        }
        if (StringUtils.hasText(this.email)) {
            super.putNoNull("LIKE_email", this.email, map);
        }
        if (StringUtils.hasText(this.password)) {
            super.putNoNull("LIKE_password", this.password, map);
        }
        super.putNoNull("EQ_age", this.age, map);
    }

}