package ${packageName};

import java.util.Map;

import org.springframework.util.StringUtils;

import com.rong.barry.base.BaseSearchDto;

import lombok.Data;
import lombok.EqualsAndHashCode;
<#list imports as import>
import ${import};
</#list>

/**
 *  ${entity.className} Dto generated by auto
 * ${comments}
 *
 * @author ${author}
 * Created On ${date}.
 */
@Data
@EqualsAndHashCode(callSuper = false)
public class ${className} extends BaseSearchDto{


    <#if entity.fields?? && (entity.fields?size > 0)>
    <#list entity.fields as f>
    /**
     * TODO 字段信息描述
     */
    private ${f.className} ${f.name};

    </#list>
    </#if>
    /**
     * 实现父类的查询条件过滤
     * 
     */
    @Override
    public void buildSearchParams(Map<String, Object> map) {
        <#if entity.fields?? && (entity.fields?size > 0)>
    <#list entity.fields as f>
    <#if f.className == "String">
        if (StringUtils.hasText(this.${f.name})) {
            putNoNull("LIKE_${f.name}", this.${f.name}, map);
        }
    <#else>
        putNoNull("EQ_${f.name}", this.${f.name}, map);
    </#if>
    </#list>
    </#if>
    }

}