package ${packageName};

import java.util.Map;
import java.util.Optional;

import com.rong.barry.base.BaseDto;

import lombok.Data;
import lombok.EqualsAndHashCode;
<#list imports as import>
import ${import};
</#list>
import java.util.HashMap;

/**
 *  ${entity.className} Dto generated by auto
 * ${comments}
 *
 * @author ${author}
 * Created On ${date}.
 */
@Data
@EqualsAndHashCode(callSuper=false)
public class ${className} extends BaseDto{

    /**
     * 
     */
    private static final long serialVersionUID = -1L;

    <#if entity.fields?? && (entity.fields?size > 0)>
    <#list entity.fields as f>
    /**
     * TODO 字段信息描述
     */
    private ${f.className} ${f.name};

    </#list>
    </#if>
    /**
     * 获取查询条件与值
     * 
     */
    public Map<String, Object> getSearchParams() {
        Map<String, Object> map = new HashMap<>();
        
        return map;
    }

    public void putNoNull(String key, Object value, Map<String, Object> map) {
        Optional.ofNullable(value).ifPresent(a -> map.put(key, a));
    }
}