package ${packageName};

import java.util.List;
import java.util.Map;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Sort.Direction;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.rong.barry.base.BaseService;
import com.rong.barry.base.PageInfo;
import ${entity.packageName}.${entity.className};
import ${lastRenderResponse.form.packageName}.${lastRenderResponse.form.className};
import ${lastRenderResponse.search.packageName}.${lastRenderResponse.search.className};

import lombok.extern.slf4j.Slf4j;

/**
 * service for ${entity.className} generated by jpa-codegen
 * ${comments}
 *
 * @author ${author}
 * Created On ${date}.
 */
@Slf4j
@Service
@Transactional(readOnly = true)
public class ${className} extends BaseService<${entity.className}, ${entity.id.className}> {

    //@Autowired
    //private ${lastRenderResponse.repository.className} ${lastRenderResponse.repository.className?uncap_first};

    /**
     * 创建实体
     *
     * @param ${lastRenderResponse.form.className?uncap_first} 表单
     * @return 实体对象
     */
    @Transactional(readOnly = false)
    public ${entity.className} create(${lastRenderResponse.form.className} ${lastRenderResponse.form.className?uncap_first}) {
        ${entity.className} ${entity.className?uncap_first} = new ${entity.className}();
        mapper(${entity.className?uncap_first}, ${lastRenderResponse.form.className?uncap_first});
        return save(${entity.className?uncap_first});
    }

    /**
     * 删除实体
     * @param id 实体id
     */
    @Transactional(readOnly = false)
    public void deleteById(${entity.id.className} id) {
        delete(id);
    }

    /**
     * 更新实体
     *
     * @param form 表单
     * @param id      实体id
     * @return 实体对象
     */
    @Transactional(readOnly = false)
    public ${entity.className} update(${entity.id.className} id, ${lastRenderResponse.form.className} ${lastRenderResponse.form.className?uncap_first}) {
        ${entity.className} ${entity.className?uncap_first} = details(id);
        mapper(${entity.className?uncap_first}, ${lastRenderResponse.form.className?uncap_first});
        return save(${entity.className?uncap_first});
    }

    /**
     * 获取一个实体对象
     *
     * @param id 实体id
     * @return 实体对象
     */
    public ${entity.className} details(${entity.id.className} id) {
        return findOne(id).orElseGet(() -> new ${entity.className}());
    }

    /**
     * 分页列表
     * 
     * @param searchParams 搜索参数
     * @param pageInfo     分页信息
     * @return 分页列表
     */
    public Page<${entity.className}> getPageList(Map<String, Object> searchParams, PageInfo pageInfo) {
        ${entity.className}SearchDto searchDto = conver(searchParams, ${entity.className}SearchDto.class);
        Map<String, Object> searchmap = searchDto.getSearchParams();
        log.debug("${entity.className}的分页搜索的条件是={},排序的字段为={}", searchmap, pageInfo.getSortType());
        return getPage(searchmap, pageInfo.getNumber(), pageInfo.getSize(), Direction.DESC,
                pageInfo.getSortType().split(","));
    }
    
    /**
     * 根据搜索条件搜索所有符合条件的信息列表
     * 
     * @param searchParams 搜索参数
     * @return 信息列表
     */
    public List<${entity.className}> findByParams(Map<String, Object> searchParams) {
        ${entity.className}SearchDto searchDto = conver(searchParams, ${entity.className}SearchDto.class);
        log.debug("${entity.className}的不分页搜索的参数是={}", searchDto);
        return findAllByMapParams(searchDto.getSearchParams(), Direction.DESC, "id");
    }
}